---
- name: create django project
  sudo_user: '{{ app_user }}'
  command: '{{ virtualenv_path }}/exec django-admin startproject {{ app_name }}'
  args:
    chdir: '{{ app_user_home }}'
    creates: '{{ app_user_home }}/{{ app_name }}'

- name: copy uwsg file
  sudo_user: '{{ app_user }}'
  template: src=uwsgi.j2 dest={{ project_dir }}/uwsgi_{{ app_name }}.ini owner={{ app_user }}

- name: copy settings.py
  sudo_user: '{{ app_user }}'
  template: src=settings.j2 dest={{ project_dir }}/{{ app_name }}/settings.py

- name: migrate database
  sudo_user: '{{ app_user }}'
  django_manage: command=migrate virtualenv={{ virtualenv_path }} app_path={{ project_dir }}

- name: supervisor config
  sudo_user: 'root'
  template: src=supervisor.j2 dest=/etc/supervisor/conf.d/{{ app_name }}.conf
  notify:
    - restart supervisor
