---
- name: create PostgreSQL user
  postgresql_user: >
    name={{ db_user }} 
    password={{ db_user_password }} 
    priv=ALL
    role_attr_flags=CREATEDB
  notify:
    - restart postgresql

- name: create PostgreSQL database
  postgresql_db: >
    name={{ db_name }}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
  notify:
    - restart postgresql
